apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app
type: Opaque
stringData:
  BACKEND_API_KEY: "super-secret-api-key-change-in-prod" #there is no such need of this API Key it's jyust mentioned to demonstrate the use of Secrets in K8's

  # If MongoDB were attached, secrets would look like this: 
  #
  # MongoDB connection string
  # MONGO_URI: "mongodb://admin:password@mongo-service:27017/appdb"
  #
  # MongoDB username and password
  # MONGO_USERNAME: "admin"
  # MONGO_PASSWORD: "supersecretpassword"
  #
  # And in backend/deployment.yaml you would add under env:
  #   - name: MONGO_URI
  #     valueFrom:
  #       secretKeyRef:
  #         name: backend-secret
  #         key: MONGO_URI
